### ISSUE TITLE
Unable to open game

### ISSUE THREAD

**Issue by jxwdsb** [Real-Ascarre/UE4-Apk-Dumper#1]
Unable to open game
Apex 英雄M 1.1.839.123
com.levelinfinite.apexlegendsmobile
https://apexm.hk/

Follow the video tutorial, unable to open the game
Add the classes4.dex file and run the game successfully. However, modify classes.dex cannot open the game

**Comment by Real-Ascarre** [comment]
The Game has a check in the libanort.so file which causes crashes when you modify the dex file. You need to manually bypass it to get inside the game. But you can Dump in login too just it won't be a full sdk dump.

**Comment by jxwdsb** [comment]
how dump in login?

**Comment by jxwdsb** [comment]
> The Game has a check in the libanort.so file which causes crashes when you modify the dex file. You need to manually bypass it to get inside the game. But you can Dump in login too just it won't be a full sdk dump.

如何转储登录？

**Comment by Real-Ascarre** [comment]
Kill signature using MT Manager or similar way then add the dumper dex and lib and add permissions and open game. You can go till login.
You can dump the sdk in login..

**Comment by jxwdsb** [comment]
> Kill signature using MT Manager or similar way then add the dumper dex and lib and add permissions and open game. You can go till login. You can dump the sdk in login..

I have an MT app member. I did, but I can't open the game and enter the login interface

**Comment by Real-Ascarre** [comment]
@Ascarre send me what you doing on tlg

**Comment by jxwdsb** [comment]
> @Ascarre send me what you doing on tlg

thk ， I have contacted TG

**Comment by stayperfection** [comment]
> > @Ascarre send me what you doing on tlg
> 
> thk ， I have contacted TG

Hello, have you solved it? I'm also playing this game. Is it convenient for tg to communicate?

**Comment by jxwdsb** [comment]
> 

Not resolved ...

**Comment by jxwdsb** [comment]
> > > @Ascarre send me what you doing on tlg
> > 
> > 
> > thk ， I have contacted TG
> 
> Hello, have you solved it? I'm also playing this game. Is it convenient for tg to communicate?

Not resolved

**Comment by stayperfection** [comment]
> 



> Have you tried other dump tools to facilitate tg's communication?

**Comment by stayperfection** [comment]
> > > > @Ascarre send me what you doing on tlg
> > > 
> > > 
> > > thk ， I have contacted TG
> > 
> > 
> > Hello, have you solved it? I'm also playing this game. Is it convenient for tg to communicate?
> 
> Not resolved ，They didn't solve the problem. He said that MT was used to remove the signature. I tried, but it was useless

Have you tried other dump tools to facilitate tg's communication?

**Comment by Real-Ascarre** [comment]
Hey the crash issue due to changing the dex is because of integrity check so its not my problem to fix that issue as it depends from game to gam, you need to bypass it  by yourself. I sent you a video on how i killed the sign and its working. this is just the dumper not the sign bypass. figure it our on how to kill the sign. use mt manager np manager or own source.

**Comment by stayperfection** [comment]
> 

Will you update the sdk of this game?

**Comment by stayperfection** [comment]
> Hey the crash issue due to changing the dex is because of integrity check so its not my problem to fix that issue as it depends from game to gam, you need to bypass it by yourself. I sent you a video on how i killed the sign and its working. this is just the dumper not the sign bypass. figure it our on how to kill the sign. use mt manager np manager or own source.

Will you update the sdk of this game?

**Comment by Real-Ascarre** [comment]
If i get time i will do update it..

**Comment by stayperfection** [comment]
> Unable to open game Apex 英雄M 1.1.839.123 com.levelinfinite.apexlegendsmobile https://apexm.hk/
> 
> Follow the video tutorial, unable to open the game Add the classes4.dex file and run the game successfully. However, modify classes.dex cannot open the game


Do you know how to update the offset of this game? I use the dumper tool to have the world and name, but the dump can't get the data. I think it's because of the offset problem. Do you know how to fix it?

**Comment by Real-Ascarre** [comment]
Dump the lib using the lib-dumper and send me the Ida Loaded lib will find it for ya.

**Comment by stayperfection** [comment]
> Dump the lib using the lib-dumper and send me the Ida Loaded lib will find it for ya.


I used the dumper tool to print it and found that the structure is correct, only the className is garbled, I tried to fix it and could not fix it successfully. I dumper the libue4 of the game directly and it also prompts an error. I think the error is caused by the offset. I will send you the original libue4 of the game to TG. Can you see it?

**Comment by stayperfection** [comment]
> Dump the lib using the lib-dumper and send me the Ida Loaded lib will find it for ya.

i have solved

**Comment by jxwdsb** [comment]
> > Dump the lib using the lib-dumper and send me the Ida Loaded lib will find it for ya.
> 
> i have solved

How did you solve it

**Comment by Real-Ascarre** [comment]
Nice.

**Comment by stayperfection** [comment]
> Nice.

I'd like to ask two questions, if it's convenient for you to answer them. 
1. pubg_mobile This game will be closed due to fuzzy values, so it is impossible to locate the world. I tried to use the disconnection operation, but there will be a disconnection prompt dialog box, which will cause the uncontrollable character to blur the next step. Want to know how you found the world, did you reverse libue4? 
2. gname, my idea is to search the characteristic string (for example, None), but this method seems to be only part of the game. In my test, apex can be located by this method, but I found that pubg_mobile can't be located by this method. Can you share the method, or use ida to unlock libue4 to see it?

thank you！

**Comment by Real-Ascarre** [comment]
In pubg mobile the global pointer are encrypted for reversers to find, you need to manually reverse the getGnames function to get gnames or find a dynamic pointer and add some offsets to it like we used a pointer + 0x80
GWorld is also hidden the same way, i dont play pubg and its also ban in my country so i dont think unless a unban comes i will be able to reverse the game and infact i dont like the game anyways.

Pubg is made in 4.18.1 UE4 source so to know more you can read the official source to get an idea. 
apex is on 4.23.1 UE4 Version.

**Comment by stayperfection** [comment]
> 



> In pubg mobile the global pointer are encrypted for reversers to find, you need to manually reverse the getGnames function to get gnames or find a dynamic pointer and add some offsets to it like we used a pointer + 0x80 GWorld is also hidden the same way, i dont play pubg and its also ban in my country so i dont think unless a unban comes i will be able to reverse the game and infact i dont like the game anyways.
> 
> Pubg is made in 4.18.1 UE4 source so to know more you can read the official source to get an idea. apex is on 4.23.1 UE4 Version.

OK, thanks, I've solved it.
